site_name: Aldo Socarras
site_url: https://driuft.com
site_description: "Android Engineer at Square with a passion for accessibility, performance, and all things mobile. Building impactful apps and sharing random thoughts."
site_author: Aldo Socarras

copyright: <p>Copyright &copy; 2024 - 2025 Aldo Socarras</p>

nav:
  - Welcome: index.md
  - Experience: experience/index.md
  - Speaking: speaking/index.md
  - Blog: blog/index.md

theme:
  name: material
  language: en
  font:
    text: Noto Sans
    code: Roboto Mono
  favicon: assets/images/favicon.svg
  logo: assets/images/logo-white.png
  icon:
    search: material/magnify
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      primary: black
      toggle:
        icon: material/lightbulb-auto
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode

  features:
    - announce.dismiss
    - content.tooltips
    - header.autohide
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.prune
    - navigation.indexes
    - navigation.top
    - search.suggest
    - search.highlight

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - footnotes
  - md_in_html
  - neoteroi.timeline
  - pymdownx.blocks.caption
  - pymdownx.details
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true

extra:
  generator: true
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/driuft
    - icon: fontawesome/brands/bluesky
      link: https://bsky.app/profile/driuft.com
    - icon: fontawesome/brands/mastodon
      link: https://androiddev.social/@driuft
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/driuft
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/airsocarras

extra_css:
  - stylesheets/extra.css
  - stylesheets/neoteroi-mkdocs.css

plugins:
  - blog:
      authors: false
  - search
  - tags

watch:
  - includes
